### ISSUE TITLE
Update sensors Africa website

### ISSUE THREAD

**Issue by usmanbiu** [CodeForAfrica/sensors.AFRICA#333]
## Description

The following updates are required for the page on AIR on the sensors.Africa [website](https://sensors.africa/air)

1. Update the showcase section of the sensors website to include recent events such as the [air quality hackathon](https://www.hacktotherescue.org/challenges) and the [DW story on ](https://www.dw.com/en/the-fight-for-clean-air-by-tackling-pollution-in-nairobi/video-68350720)sensors Africa.
2. Add Ghana as an option on the dropdown menu to search for cities where sensors are located. See screenshot [below]
![Screenshot from 2024-03-04 09-39-53](https://github.com/CodeForAfrica/sensors.AFRICA/assets/69766740/5f5b46ed-86a5-44cf-b29a-06e28ca72c85) 
3. Move the tabs on "DATA" , "STORIES" and "MONTHLY AIR REPORTS" from the drop-down on the top right corner of the page to the main body of the page for easier access (they're not easily noticeable in their current location)![Screenshot from 2024-03-04 09-50-06](https://github.com/CodeForAfrica/sensors.AFRICA/assets/69766740/ee41c862-716c-472e-bd2f-38c3ba9b3917)

4.  Update the " MONTHLY AIR REPORTS' section to include reports for [2023](https://lookerstudio.google.com/u/0/reporting/85d75afc-595f-4fe9-bca7-7f3a1de2eeb6/page/Su9vC) and [2024](https://lookerstudio.google.com/u/0/reporting/9ad1ed61-1af5-4828-8cac-cea5cce4ed23/page/Su9vC).  The monthly air reports section currently only links to the reports for 2022, could we have that tab on the main page as requested above, and possibly with dropdowns to select specific report to view (i.e report for 2022, or 2023, or 2024)

## Files

1. Files for the showcase section - src/components/Showcase
2.  File for adding cities to the drop-down - src/pages/air/city/[id].js 
3. File to the current location for DATA and MONTHLY AIR REPORTS - src/components/Hambuger/HambugerMenu.js

## To Reproduce

If this issue is describing a bug, include some steps to reproduce the behavior.

## Tasks

Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.

- [x] Update the showcase section
- [ ] Add Ghana to the list of cities
- [ ] Move the tabs on "DATA", "STORIES" and "MONTHLY REPORTS" to the main page
- [ ] Add the option to select the specific monthly report to view with links to the reports

**Comment by kilemensi** [comment]
Who is this assigning me tasks that I have zero context of?

If I'm not mistaken @usmanbiu :

1. Showcase articles are loaded from a [gSheet](https://docs.google.com/spreadsheets/d/1I2nTG_lst4nYrg8z1e7RaolC16A-M7f_lO_zRaV9L5s/edit?usp=drive_web&ouid=113130591356813333472). You can edit them there.
2. Which cities from Ghana need to be added?
3. That's a design change that should be discussed separately e.g. how will it work across different screen sizes, etc.
4. Was the current 2022 report designed by us i.e. the Tech team?

**Comment by usmanbiu** [comment]
Appologies @kilemensi .
It's something we are still working on and I was not supposed to do that yet.
Also thanks for the additional info

**Comment by gideonmaina** [comment]
@usmanbiu This [branch aims](https://github.com/CodeForAfrica/sensors.AFRICA/tree/Update/City-Ghana) to update Ghana cities. A separate issue on the same will be appropriate. Mortality statistics for Ghana, both general and child mortality statistics, are required for a PR to be made. This needs a little research or a consensus on whether this information is useful or not based on the availability of the data for each country where sensors are deployed. 

As so for Kenya : 
<img width="264" alt="Screenshot 2024-03-05 at 17 31 46" src="https://github.com/CodeForAfrica/sensors.AFRICA/assets/17834362/b7bed622-083b-4a8d-bade-2a518ec70c17">

Otherwise, such an error will occur.
<img width="937" alt="Screenshot 2024-03-05 at 17 29 44" src="https://github.com/CodeForAfrica/sensors.AFRICA/assets/17834362/31c3c40e-c91d-4c62-a243-d4b7c3ab304d">
I can only go as far as updating the cities.
<img width="349" alt="Screenshot 2024-03-05 at 17 28 31" src="https://github.com/CodeForAfrica/sensors.AFRICA/assets/17834362/fb3d1986-bc1b-46f8-a818-364e7dd0b62d">

**Comment by usmanbiu** [comment]
The showcase section has been updated

**Comment by kilemensi** [comment]
If at all possible @usmanbiu, make the summaries shorter (or at least have similar-ish length).
![Uploading Screenshot 2024-03-13 at 16.57.03.png…]()

**Comment by usmanbiu** [comment]
This issue is being closed as it has been split into issues #334 , #335 , #336, #337, and 3338 for a better workflow.
