### ISSUE TITLE
Update the carousel for the showcase section of the sensors website

### ISSUE THREAD

**Issue by usmanbiu** [CodeForAfrica/sensors.AFRICA#335]
## Description

Update the carousel for the showcase section of the sensors website. It is currently not noticeable (unapparent) and visitors to the website will miss out on previous stories in that section (they would not know that they can slide sideways to view more stories/articles). An alternative could be to add pagination to the section.

## Screenshots
![Screenshot from 2024-03-13 15-14-00](https://github.com/CodeForAfrica/sensors.AFRICA/assets/69766740/25761892-dede-450c-a419-e41254383fdb)

## Files

src/components/Showcase

## To Reproduce

1.     Go to the sensors.Africa website
2.     Click on AIR
3.     Scroll down to the showcase section and you will notice that the carousel is unapparent/hidden

## Tasks

- [ ] Enlarge the carousel or add pagination
- [ ] Add arrows at both ends (left and right) of the showcase sections that show that there is an option to slide sideways to view more content
- [ ] Reduce the opacity of the arrows so as not to obstruct page content.

**Comment by gideonmaina** [comment]
This a design change at @usmanbiu. Tagging UI devs from tech would be useful to help in drawing some inspiration.

What I am anticipating is a conversation about the current layout design and whether it is suitable when the number of stories increases.

**Comment by usmanbiu** [comment]
@gideonmaina I noticed that you made a change to the carousel. it looks much better
