### ISSUE TITLE
Update the " MONTHLY AIR REPORTS' section of the website to include reports for 2023 and 2024

### ISSUE THREAD

**Issue by usmanbiu** [CodeForAfrica/sensors.AFRICA#337]
## Description
Update the " MONTHLY AIR REPORTS' section to include reports for [2023](https://lookerstudio.google.com/u/0/reporting/85d75afc-595f-4fe9-bca7-7f3a1de2eeb6/page/Su9vC) and [2024](https://lookerstudio.google.com/u/0/reporting/9ad1ed61-1af5-4828-8cac-cea5cce4ed23/page/Su9vC). The monthly air reports section currently only links to the reports for 2022, could we have that tab on the main page as requested in issue #336 , and possibly with dropdowns to select specific report to view (i.e report for 2022, or 2023, or 2024)

## Screenshots
![Screenshot from 2024-03-04 09-50-06](https://github.com/CodeForAfrica/sensors.AFRICA/assets/69766740/7e38f614-9dd3-44bf-bbfe-c43adbade094)

## Files
src/components/Hambuger/HambugerMenu.js

## To Reproduce

1. Go to the sensors.Africa website
2. Click on the tab on the top right corner of the webpage

## Tasks

- [ ] Add a dropdown to place the multiple reports 
- [ ] Add links to the reports
- [ ] Depending on how issue #336 is to be handled, the reports tab is to be moved to the main page as requested in issue #336.

**Comment by usmanbiu** [comment]
@gideonmaina I want to swap the 2023 report with that of 2024 before we complete the final enhancements.

**Comment by gideonmaina** [comment]
@usmanbiu confirm the reports are displayed as expected.

**Comment by usmanbiu** [comment]
hi @gideonmaina  we now need to swap the reports with those of 2025,
(2025 report - https://lookerstudio.google.com/u/1/reporting/b38f31a6-40c7-4fd6-9136-7e8907984f61/page/Su9vC?access=viewer&requester=fatimohafolabi2019@gmail.com)
